version: 2
jobs:
  build:

    working_directory: /tmp/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

      - run: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "fa:49:ca:3a:f3:48:9b:e5:02:f3:07:c3:4b:23:95:f4"

      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:akos-circleci-java.git HEAD:refs/heads/master
            heroku restart

  # deploy:
  #
  #   working_directory: /tmp/circleci-demo-java-spring
  #
  #   docker:
  #     - image: circleci/openjdk:8-jdk-browsers
  #     - image: circleci/postgres:9.6.3-alpine
  #
  #   steps:
  #
  #
  #
# workflows:
#    version: 2
#    build-deploy:
#      jobs:
#        - build
#        - deploy:
#            requires:
#              - build
#            filters:
#              branches:
#                only: master
